version: "3.8"

services:
  database:
    image: postgres
    ports:
      - "5432:5432"
    restart: always

    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: taskdb
    volumes:
    - db_data:/var/lib/postgresql/data
     - /init.sql:/docker-entrypoint-initdb.d/db
   networks:
     - app-network

 app:
   build: ./app
   ports:
     - "5000:5000"
   environment:
     - NAME=World
   depends_on:
     - database
   networks:
     - app-network

networks:
 app-network:
   driver: bridge

volumes:
 db_data:
